spring.application.name=restapi\

spring.datasource.url = jdbc:postgresql://localhost:5432/restapi_db
spring.datasource.username=postgres
spring.datasource.password=mysql1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
